translations = {
    "of_houses": "Домов:",
    "details_of_flats": "Квартир:",
    "text_flat": "Квартира",
    "text_project": "Проект",
    "text_house": "Дом",
    "text_houses": "Дома",
    "text_city": "Город",
    "text_specials": "Характеристики",
    "text_floor": "Этаж",
    "text_flat_layout": "Планировка",
    "text_offers": "Предложения",
    "no_offers": "Нет предложений",
    "text_corpus": "Корпус",
    "text_phase": "Очередь",
    "text_floors": "Этажность",
    "text_deadline": "Срок сдачи",
    "text_deadline_year": "Год",
    "text_house_structure_type": "Тип",
    "text_building_status": "Статус",
    "text_parking": "Паркинг",
    "text_lift": "Лифт",
    "text_layouts": "Планировки",
    "text_roomcols": "комнатные",
    "text_developer": "Застройщик",
    "text_location": "Локация",
    "text_description": "Описание",
    "text_coordinates": "Местоположение комплекса",
    "text_exterrior": "Экстерьер комплекса",
    "choose_flat": "Выбрать квартиру в",

    "projects": "Проекты",
    "contacts": "Контакты",
    "departments": "Отделы",
    "prices": "Цены:",

    "lead_ticket": "Оставьте заявку",
    "for_view": "На просмотр",
    "for_choose": "На подбор",
}