# Generated by Django 5.2.12 on 2026-04-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='deadline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
