# Generated by Django 5.2.12 on 2026-04-03 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('houses', '0003_alter_house_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='address',
        ),
        migrations.RemoveField(
            model_name='house',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='house',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='house',
            name='floors',
        ),
        migrations.RemoveField(
            model_name='house',
            name='phase',
        ),
        migrations.AlterField(
            model_name='house',
            name='external_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='HouseParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('corpus', models.CharField(blank=True, max_length=255, null=True)),
                ('phase', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline', models.CharField(blank=True, max_length=50, null=True)),
                ('deadline_year', models.IntegerField(blank=True, null=True)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('lift', models.IntegerField(blank=True, null=True)),
                ('parking', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('building_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.buildingstatus')),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='houses.house')),
                ('house_structure_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.housestructuretype')),
            ],
        ),
    ]
