# Generated by Django 5.2.12 on 2026-04-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_remove_house_address_remove_house_corpus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseparams',
            name='lift',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseparams',
            name='parking',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
