# Generated by Django 5.2.12 on 2026-04-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_alter_houseparams_lift_alter_houseparams_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houseparams',
            name='plan',
            field=models.URLField(blank=True, null=True),
        ),
    ]
