# Generated by Django 5.2.12 on 2026-04-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_house_image_houseparams_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseparams',
            name='plan',
        ),
        migrations.AddField(
            model_name='house',
            name='plan',
            field=models.URLField(blank=True, null=True),
        ),
    ]
