# Generated by Django 5.2.13 on 2026-04-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_remove_houseparams_plan_house_plan'),
        ('projects', '0006_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
