# Generated by Django 5.2.13 on 2026-04-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_house_slug_alter_house_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
