# Generated by Django 5.2.13 on 2026-04-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_alter_house_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='house',
            unique_together=set(),
        ),
    ]
