# Generated by Django 5.2.13 on 2026-04-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_alter_house_unique_together'),
        ('projects', '0008_alter_project_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('project', 'slug')},
        ),
    ]
