# Generated by Django on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="HtmlModule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Идентификатор")),
                ("code", models.TextField(verbose_name="HTML содержимое")),
            ],
            options={
                "verbose_name": "HTML модуль",
                "verbose_name_plural": "HTML модули",
            },
        ),
    ]