# Generated by Django 4.2 on 2026-08-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0002_alter_htmlmodule_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterMenuItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("url", models.CharField(max_length=255, verbose_name="URL")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("module", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="footer_menu_items", to="core.module", verbose_name="Модуль")),
            ],
            options={
                "verbose_name": "Пункт меню футера",
                "verbose_name_plural": "Пункты меню футера",
                "ordering": ["order", "id"],
            },
        ),
    ]
