# Generated by Django 4.2 on 2026-08-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_parserrun_flats_deactivated"),
        ("modules", "0002_alter_htmlmodule_id"),
        ("estates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagsMenu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок меню")),
                ("module", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="tags_menu", to="core.module", verbose_name="Модуль")),
            ],
            options={
                "verbose_name": "Меню тегов",
                "verbose_name_plural": "Меню тегов",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TagsMenuItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("tag", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tags.Tag", verbose_name="Тег")),
                ("tags_menu", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="modules.tagsmenu", verbose_name="Меню тегов")),
            ],
            options={
                "verbose_name": "Пункт меню тегов",
                "verbose_name_plural": "Пункты меню тегов",
                "ordering": ["order", "id"],
            },
        ),
    ]
