# Generated by Django 5.2.17 on 2026-08-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_footermenuitem'),
        ('modules', '0013_tagsmenu_tagsmenuitem'),
    ]

    operations = [
    ]
