# Generated by Django 5.2.17 on 2026-08-18 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_parserrun_flats_deactivated'),
        ('documents', '0005_alter_document_document_date'),
        ('modules', '0014_merge_0012_footermenuitem_0013_tagsmenu_tagsmenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDescriptionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок формы')),
                ('message_tpl', models.TextField(blank=True, help_text='Префикс перед комментарием пользователя', null=True, verbose_name='Шаблон сообщения')),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email для отправки')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_description_settings', to='core.module', verbose_name='Модуль')),
                ('personal_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_description_personal_data', to='documents.document', verbose_name='Обработка персональных данных')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_description_policy', to='documents.document', verbose_name='Политика конфиденциальности')),
            ],
            options={
                'verbose_name': 'Настройки описания проекта',
                'verbose_name_plural': 'Настройки описания проекта',
            },
        ),
    ]
