# Generated by Django 5.2.17 on 2026-08-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0015_add_project_description_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdescriptionsettings',
            name='header_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Заголовок для 'Узнать подробнее'"),
        ),
        migrations.AddField(
            model_name='projectdescriptionsettings',
            name='message_tpl_info',
            field=models.TextField(blank=True, null=True, verbose_name="Шаблон сообщения для 'Узнать подробнее'"),
        ),
    ]
