# Generated by Django 5.2.17 on 2026-08-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_phones'),
        ('modules', '0016_add_project_description_info_fields'),
        ('tags', '0006_autotagtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('quantity', models.PositiveIntegerField(default=10, verbose_name='Количество на странице')),
                ('random', models.BooleanField(default=False, verbose_name='Случайный порядок')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tag_collection', to='core.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Подборка тегов',
                'verbose_name_plural': 'Подборки тегов',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TagCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='modules.tagcollection', verbose_name='Подборка')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tags.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег подборки',
                'verbose_name_plural': 'Теги подборки',
                'ordering': ['order', 'id'],
            },
        ),
    ]
