# Generated by Django 5.2.16 on 2026-07-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('yandex', 'Яндекс Карты'), ('2gis', '2GIS')], default='yandex', max_length=20, verbose_name='Поставщик карт')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('language', models.CharField(default='ru_RU', max_length=20, verbose_name='Язык')),
                ('default_zoom', models.PositiveSmallIntegerField(default=16, verbose_name='Zoom')),
                ('default_height', models.PositiveSmallIntegerField(default=450, verbose_name='Высота карты')),
                ('show_controls', models.BooleanField(default=True, verbose_name='Показывать элементы управления')),
                ('clusterize', models.BooleanField(default=True, verbose_name='Объединять маркеры')),
                ('enabled', models.BooleanField(default=True, verbose_name='Использовать карты')),
            ],
            options={
                'verbose_name': 'Настройки карт',
                'verbose_name_plural': 'Настройки карт',
                'db_table': 'core_mapsettings',
            },
        ),
    ]
