# Generated by Django 5.2.16 on 2026-07-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsettings',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Secret Key'),
        ),
    ]
