# Generated by Django 5.2.17 on 2026-08-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_contacttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код страны (ISO)')),
                ('phone_code', models.CharField(help_text='Цифры без плюса. Например: 7, 375, 380', max_length=10, verbose_name='Телефонный код')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
    ]
