# Generated by Django 5.2.16 on 2026-08-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255, verbose_name='Название документа')),
                ('document_content', models.TextField(verbose_name='HTML содержимое')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл документа')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('document_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-document_date', '-id'],
            },
        ),
    ]
