# Generated by Django 5.2.16 on 2026-08-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_date',
            field=models.DateField(auto_now=True, default='1964-07-08', verbose_name='Дата документа'),
            preserve_default=False,
        ),
    ]
