# Generated by Django 5.2.16 on 2026-08-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_document_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата документа'),
        ),
    ]
