# Generated by Django 5.2.16 on 2026-08-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_document_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_public',
            field=models.BooleanField(default=False, verbose_name='Публичный'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_status',
            field=models.CharField(choices=[('project', 'Проект'), ('released', 'Выпущен')], default='project', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_date',
            field=models.DateField(auto_now=True, null='True', verbose_name='Дата документа'),
        ),
    ]
