# Generated by Django 5.2.17 on 2026-08-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_document_public_document_document_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата документа'),
        ),
    ]
