# Generated by Django 4.2 on 2026-08-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0013_project_origin_parser_project_origin_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Тег")),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_tags", to="projects.project")),
                ("tag", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_tags", to="tags.tag")),
            ],
            options={
                "verbose_name": "Тег проекта",
                "verbose_name_plural": "Теги проектов",
                "unique_together": {("project", "tag")},
            },
        ),
    ]
