# Generated by Django 5.2.17 on 2026-08-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='robots_follow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='robots_index',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='seo_h1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
