# Generated by Django 5.2.17 on 2026-08-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
        ('tags', '0004_tag_created_at_tag_created_by_tag_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_tags', to='flats.flat')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_tags', to='tags.tag')),
            ],
            options={
                'verbose_name': 'Тег квартиры',
                'verbose_name_plural': 'Теги квартир',
                'unique_together': {('flat', 'tag')},
            },
        ),
    ]
