# Generated by Django 5.2.17 on 2026-08-24 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_flattag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTagTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('flat', 'Квартира'), ('project', 'Проект')], max_length=20, verbose_name='Тип объекта')),
                ('autostart', models.BooleanField(default=False, verbose_name='Автостарт')),
                ('triggers', models.JSONField(blank=True, default=list, verbose_name='Признаки')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_tasks', to='tags.tag')),
            ],
            options={
                'verbose_name': 'Автотег задание',
                'verbose_name_plural': 'Автотег задания',
                'ordering': ['id'],
            },
        ),
    ]
