# Generated by Django 5.2.17 on 2026-08-11 12:04

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developers', '0007_developer_origin_parser_developer_origin_type'),
        ('flats', '0021_flat_origin_parser_flat_origin_type'),
        ('houses', '0013_house_origin_parser_house_origin_type'),
        ('projects', '0014_project_tags'),
        ('tags', '0002_alter_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Застройщик',
                'verbose_name_plural': 'Застройщики',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('developers.developer',),
        ),
        migrations.CreateModel(
            name='FlatProxy',
            fields=[
            ],
            options={
                'verbose_name': 'flat',
                'verbose_name_plural': 'flats',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('flats.flat',),
        ),
        migrations.CreateModel(
            name='HouseProxy',
            fields=[
            ],
            options={
                'verbose_name': 'house',
                'verbose_name_plural': 'houses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('houses.house',),
        ),
        migrations.CreateModel(
            name='ProjectProxy',
            fields=[
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.project',),
        ),
        migrations.CreateModel(
            name='TagProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tags.tag',),
        ),
    ]
