# Generated by Django 5.2.16 on 2026-07-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_module_options_alter_module_is_active_and_more'),
        ('core', '0004_parser_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.module',),
        ),
        migrations.AddField(
            model_name='parserrun',
            name='developers_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parserrun',
            name='developers_updated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parserrun',
            name='flats_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parserrun',
            name='flats_updated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parserrun',
            name='houses_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parserrun',
            name='houses_updated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parserrun',
            name='projects_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parserrun',
            name='projects_updated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
