# Generated by Django 5.2.16 on 2026-07-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_module_parserrun_developers_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserrun',
            name='traceback',
            field=models.TextField(blank=True, verbose_name='Трассировка ошибки'),
        ),
    ]
