# Generated by Django 5.2.16 on 2026-07-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_parserrun_traceback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserrun',
            name='traceback',
            field=models.TextField(blank=True, default='', verbose_name='Трассировка ошибки'),
        ),
    ]
