# Generated by Django 5.2.16 on 2026-07-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_parserrun_traceback'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='engine',
            field=models.CharField(choices=[('nmarket', 'НМаркет')], default='nmarket', max_length=30, verbose_name='Движок'),
        ),
    ]
