# Generated by Django 5.2.16 on 2026-07-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_parser_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserrun',
            name='cancel_requested',
            field=models.BooleanField(default=False, verbose_name='Запрошена остановка'),
        ),
    ]
