# Generated by Django 5.2.16 on 2026-07-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_parserrun_cancel_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='last_status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает'), ('started', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], max_length=50, verbose_name='Статус последнего запуска'),
        ),
        migrations.AlterField(
            model_name='parserrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('started', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], max_length=50, verbose_name='Статус'),
        ),
    ]
