# Generated by Django 5.2.17 on 2026-08-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_parser_last_status_alter_parserrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='turnstile_enabled',
            field=models.BooleanField(default=False, help_text='Показывать капчу Cloudflare Turnstile в форме обратной связи.', verbose_name='Включить Turnstile'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='turnstile_secret_key',
            field=models.CharField(blank=True, help_text='Секретный ключ серверной проверки. Хранится только в БД.', max_length=255, verbose_name='Секретный ключ (Secret Key)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='turnstile_site_key',
            field=models.CharField(blank=True, help_text='Публичный ключ из консоли Cloudflare. Меняется в админке без деплоя.', max_length=255, verbose_name='Ключ сайта (Site Key)'),
        ),
    ]
