# Generated by Django 5.2.17 on 2026-08-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesettings_turnstile_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserrun',
            name='flats_deactivated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]