# Generated by Django 5.2.17 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_parserrun_flats_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phones',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON-список: [{'label': 'Основной', 'value': '+7...'}]",
                verbose_name="Телефоны",
            ),
        ),
    ]
