# Generated by Django 5.2.17 on 2026-09-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='addresses',
            field=models.JSONField(blank=True, default=list, help_text="JSON-список: [{'label': 'Основной', 'value': 'ул. Ленина, д. 10'}]", verbose_name='Адреса'),
        ),
    ]
