# Generated by Django 5.2.16 on 2026-08-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('max', models.CharField(blank=True, max_length=255, null=True, verbose_name='MAX')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('work_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('work_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Обработал')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-added_at'],
            },
        ),
    ]
