# Generated by Django 5.2.16 on 2026-08-07 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_contacttype'),
        ('documents', '0004_document_document_public_document_document_status_and_more'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('hint', models.CharField(blank=True, choices=[('no_call', 'Без звонков'), ('no_voice', 'Без голосовых сообщений')], max_length=20, null=True, verbose_name='Подсказка')),
                ('manager_email', models.EmailField(max_length=254, verbose_name='Email для отправки')),
                ('message_tpl', models.TextField(blank=True, help_text='Используется как префикс перед комментарием пользователя', null=True, verbose_name='Шаблон сообщения')),
                ('contact_types', models.ManyToManyField(blank=True, help_text='Какие поля контактов показывать в форме', to='dictionaries.contacttype', verbose_name='Типы контактов')),
                ('personal_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_personal_data', to='documents.document', verbose_name='Документ обработки персональных данных')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_policy', to='documents.document', verbose_name='Документ политики конфиденциальности')),
            ],
            options={
                'verbose_name': 'Модуль обратной связи',
                'verbose_name_plural': 'Модули обратной связи',
                'ordering': ['id'],
            },
        ),
    ]
