# Generated by Django 5.2.16 on 2026-08-07 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_parser_last_status_alter_parserrun_status'),
        ('leads', '0002_feedbackmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodule',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_modules', to='core.module', verbose_name='Модуль'),
        ),
    ]
