# Generated by Django 5.2.17 on 2026-08-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_feedbackmodule_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='requested_date',
            field=models.DateField(blank=True, null=True, verbose_name='Желаемая дата'),
        ),
    ]
