# Generated by Django 5.2.13 on 2026-05-06 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
        ('dictionaries', '0003_contacttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.contacttype')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='developers.developer')),
            ],
            options={
                'db_table': 'developers_contacts',
            },
        ),
        migrations.CreateModel(
            name='DeveloperDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='developers.developer')),
            ],
            options={
                'db_table': 'developers_departments',
            },
        ),
        migrations.CreateModel(
            name='DepartmentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.contacttype')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='developers.developerdepartment')),
            ],
            options={
                'db_table': 'departments_contacts',
            },
        ),
        migrations.CreateModel(
            name='DeveloperDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_description', models.TextField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='developers.developer')),
            ],
            options={
                'db_table': 'developers_descriptions',
            },
        ),
    ]
