# Generated by Django 5.2.13 on 2026-05-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_developercontact_developerdepartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
