# Generated by Django 5.2.13 on 2026-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_developer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
