# Generated by Django 5.2.13 on 2026-05-07 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_alter_developer_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departmentcontact',
            table=None,
        ),
        migrations.AlterModelTable(
            name='developercontact',
            table=None,
        ),
        migrations.AlterModelTable(
            name='developerdepartment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='developerdescription',
            table=None,
        ),
    ]
