# Generated by Django 5.2.12 on 2026-04-06 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_developer_alter_project_external_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='projects.project')),
            ],
        ),
    ]
