# Generated by Django 5.2.12 on 2026-04-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdescription',
            name='hash',
            field=models.CharField(db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectdescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
