# Generated by Django 5.2.13 on 2026-04-17 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_currency'),
        ('projects', '0009_projectparams_property_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectparams',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.propertytype'),
        ),
    ]
