# Generated by Django 5.2.13 on 2026-05-07 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0005_alter_departmentcontact_table_and_more'),
        ('projects', '0010_projectparams_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='developers.developer'),
        ),
    ]
