# Generated by Django 5.2.13 on 2026-05-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='robots_follow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='robots_index',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_h1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
