# Generated by Django 5.2.16 on 2026-07-17 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_parser_last_status_alter_parserrun_status'),
        ('projects', '0012_project_canonical_url_project_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='origin_parser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_origin', to='core.parser', verbose_name='Парсер-источник'),
        ),
        migrations.AddField(
            model_name='project',
            name='origin_type',
            field=models.CharField(choices=[('manual', 'Ручной ввод'), ('parser', 'Парсер'), ('api', 'API'), ('import', 'Импорт')], db_index=True, default='manual', max_length=20, verbose_name='Источник создания'),
        ),
    ]
