# Generated by Django 4.2 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("projects", "0013_project_origin_parser_project_origin_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                through="tags.ProjectTag",
                to="tags.tag",
                verbose_name="Теги",
            ),
        ),
    ]
