# Generated by Django 5.2.13 on 2026-04-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('main_menu', 'Main Menu'), ('account_menu', 'Account Menu'), ('sidebar', 'Sidebar'), ('content_top', 'Content Top'), ('content_bottom', 'Content Bottom')], max_length=50)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
