# Generated by Django 5.2.13 on 2026-04-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='module',
            name='position',
            field=models.CharField(choices=[('main_menu', 'Главное меню'), ('account_menu', 'Меню аккаунта'), ('sidebar', 'Сайдбар'), ('content_top', 'Верх страницы'), ('content_bottom', 'Низ страницы')], max_length=50, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='module',
            name='route',
            field=models.CharField(blank=True, help_text='URL или начало URL, где показывать модуль. Пустое = глобальный', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='template',
            field=models.CharField(max_length=255, verbose_name='Путь к шаблону'),
        ),
    ]
