# Generated by Django 5.2.16 on 2026-08-05 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_module_options_alter_module_is_active_and_more'),
        ('modules', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='html_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='modules.htmlmodule', verbose_name='HTML модуль'),
        ),
        migrations.AddField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('latest_projects', 'Последние проекты'), ('html', 'HTML модуль')], default='latest_projects', max_length=50, verbose_name='Тип модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='position',
            field=models.CharField(choices=[('main_menu', 'Главное меню'), ('account_menu', 'Меню аккаунта'), ('sitename', 'Заголовок сайта'), ('search', 'Поиск по сайту'), ('sidebar', 'Сайдбар'), ('content_top', 'Верх страницы'), ('content_bottom', 'Низ страницы'), ('footer', 'Футер'), ('house_detail_map', 'Карточка дома — карта')], max_length=50, verbose_name='Позиция'),
        ),
    ]
