# Generated by Django 5.2.16 on 2026-08-07 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_module_html_module_module_type_alter_module_position'),
        ('leads', '0002_feedbackmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='feedback_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='leads.feedbackmodule', verbose_name='Модуль обратной связи'),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('latest_projects', 'Последние проекты'), ('html', 'HTML модуль'), ('feedback', 'Обратная связь')], default='latest_projects', max_length=50, verbose_name='Тип модуля'),
        ),
    ]
