# Generated by Django 5.2.16 on 2026-08-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_module_feedback_module_alter_module_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='feedback_module',
        ),
    ]
