# Generated by Django 5.2.17 on 2026-08-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_module_feedback_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('latest_projects', 'Последние проекты'), ('html', 'HTML модуль'), ('feedback', 'Обратная связь'), ('footer_menu', 'Меню футера')], default='latest_projects', max_length=50, verbose_name='Тип модуля'),
        ),
    ]
