# Generated by Django 5.2.17 on 2026-08-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_module_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('latest_projects', 'Последние проекты'), ('html', 'HTML модуль'), ('feedback', 'Обратная связь'), ('footer_menu', 'Меню футера'), ('tags_menu', 'Меню тегов'), ('project_description', 'Описание проекта')], default='latest_projects', max_length=50, verbose_name='Тип модуля'),
        ),
    ]
