# Generated by Django 5.2.17 on 2026-09-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_module_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('latest_projects', 'Последние проекты'), ('html', 'HTML модуль'), ('feedback', 'Обратная связь'), ('footer_menu', 'Меню футера'), ('tags_menu', 'Меню тегов'), ('tag_collection', 'Подборка тегов'), ('project_description', 'Описание проекта'), ('house_description', 'Описание дома'), ('flat_description', 'Описание квартиры')], default='latest_projects', max_length=50, verbose_name='Тип модуля'),
        ),
    ]
