# Generated by Django 5.2.12 on 2026-04-03 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('flats', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='rooms_alias',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='square',
        ),
        migrations.AlterField(
            model_name='flat',
            name='external_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='FlatParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('rooms_alias', models.CharField(blank=True, max_length=50, null=True)),
                ('square', models.FloatField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('ceiling_height', models.FloatField(blank=True, null=True)),
                ('living_square', models.FloatField(blank=True, null=True)),
                ('kitchen_square', models.FloatField(blank=True, null=True)),
                ('balcony_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.balconytype')),
                ('bathroom_unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.bathroomunittype')),
                ('finish_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.finishtype')),
                ('flat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='flats.flat')),
                ('property_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.propertycategory')),
                ('property_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.propertytype')),
            ],
        ),
    ]
