# Generated by Django 5.2.12 on 2026-04-06 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('flats', '0003_remove_flat_floor_remove_flat_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='deal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.dealtype'),
        ),
    ]
