# Generated by Django 5.2.12 on 2026-04-06 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('flats', '0004_flat_deal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='deal_type',
        ),
        migrations.CreateModel(
            name='FlatDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='RUR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.dealtype')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='flats.flat')),
            ],
            options={
                'unique_together': {('flat', 'deal_type')},
            },
        ),
    ]
