# Generated by Django 5.2.12 on 2026-04-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0005_remove_flat_deal_type_flatdeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatdeal',
            name='currency',
            field=models.CharField(default='RUR', max_length=50),
        ),
    ]
