# Generated by Django 5.2.12 on 2026-04-06 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_currency'),
        ('flats', '0006_alter_flatdeal_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatdeal',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.currency'),
        ),
    ]
