# Generated by Django 5.2.12 on 2026-04-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0007_alter_flatdeal_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatdeal',
            name='haggle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flatdeal',
            name='mortgage',
            field=models.BooleanField(default=True),
        ),
    ]
