# Generated by Django 5.2.12 on 2026-04-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0008_flatdeal_haggle_flatdeal_mortgage'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
