# Generated by Django 5.2.12 on 2026-04-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0009_flat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='plan',
            field=models.URLField(blank=True, null=True),
        ),
    ]
