# Generated by Django 5.2.13 on 2026-04-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0010_flat_plan'),
        ('houses', '0008_house_slug_alter_house_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
