# Generated by Django 5.2.13 on 2026-04-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0011_flat_slug_alter_flat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
