# Generated by Django 5.2.13 on 2026-04-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0012_alter_flat_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together=set(),
        ),
    ]
