# Generated by Django 5.2.13 on 2026-04-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0013_alter_flat_unique_together'),
        ('houses', '0011_alter_house_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('house', 'slug')},
        ),
    ]
