# Generated by Django 5.2.13 on 2026-04-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0014_alter_flat_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatparams',
            name='property_category',
        ),
    ]
