# Generated by Django 5.2.13 on 2026-04-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0015_remove_flatparams_property_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatparams',
            name='property_type',
        ),
    ]
