# Generated by Django 5.2.13 on 2026-04-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0017_alter_flat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
