# Generated by Django 5.2.13 on 2026-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0018_alter_flat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
